In [14]:
import tpot
import pandas as pd
from sklearn.model_selection import train_test_split
from tpot import TPOTClassifier

In [23]:
dataku = pd.read_csv('dataset_39_ecoli.csv')
dataku.head()

mcg   gvh   lip  chg   aac  alm1  alm2  class
0  0.49  0.29  0.48  0.5  0.56  0.24  0.35  b'cp'
1  0.07  0.40  0.48  0.5  0.54  0.35  0.44  b'cp'
2  0.56  0.40  0.48  0.5  0.49  0.37  0.46  b'cp'
3  0.59  0.49  0.48  0.5  0.52  0.45  0.36  b'cp'
4  0.23  0.32  0.48  0.5  0.55  0.25  0.35  b'cp'

In [24]:
dictio_cnvrt_class = {"b'cp'":0, "b'im'":1, "b'pp'":2, "b'imU'":3, "b'om'":4, "b'omL'":5, "b'imL'":6, "b'imS'":7}
dataku['class'] = dataku['class'].map(dictio_cnvrt_class)

In [25]:
Y = dataku['class'].to_numpy()
X = dataku[dataku.columns[:7]].to_numpy()

In [26]:
X

array([[0.49, 0.29, 0.48, ..., 0.56, 0.24, 0.35],
       [0.07, 0.4 , 0.48, ..., 0.54, 0.35, 0.44],
       [0.56, 0.4 , 0.48, ..., 0.49, 0.37, 0.46],
       ...,
       [0.61, 0.6 , 0.48, ..., 0.44, 0.39, 0.38],
       [0.59, 0.61, 0.48, ..., 0.42, 0.42, 0.37],
       [0.74, 0.74, 0.48, ..., 0.31, 0.53, 0.52]])

In [27]:
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       7, 7, 6, 6, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,

In [28]:
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.3,random_state=22)

In [29]:
x_train

array([[0.3 , 0.51, 0.48, ..., 0.42, 0.61, 0.34],
       [0.71, 0.52, 0.48, ..., 0.64, 1.  , 0.99],
       [0.86, 0.55, 0.48, ..., 0.63, 0.81, 0.83],
       ...,
       [0.36, 0.56, 0.48, ..., 0.43, 0.45, 0.53],
       [0.32, 0.39, 0.48, ..., 0.53, 0.28, 0.38],
       [0.3 , 0.44, 0.48, ..., 0.49, 0.22, 0.33]])

In [30]:
x_test

array([[0.41, 0.48, 0.48, 0.5 , 0.51, 0.44, 0.51],
       [0.29, 0.47, 0.48, 0.5 , 0.41, 0.23, 0.34],
       [0.63, 0.54, 0.48, 0.5 , 0.65, 0.79, 0.81],
       [0.45, 0.4 , 0.48, 0.5 , 0.61, 0.74, 0.77],
       [0.75, 0.84, 0.48, 0.5 , 0.35, 0.52, 0.33],
       [0.5 , 0.49, 0.48, 0.5 , 0.49, 0.46, 0.53],
       [0.59, 0.29, 0.48, 0.5 , 0.64, 0.75, 0.77],
       [0.35, 0.51, 0.48, 0.5 , 0.61, 0.71, 0.74],
       [0.74, 0.82, 0.48, 0.5 , 0.49, 0.49, 0.41],
       [0.25, 0.4 , 0.48, 0.5 , 0.47, 0.33, 0.42],
       [0.73, 0.84, 0.48, 0.5 , 0.86, 0.58, 0.29],
       [0.39, 0.32, 0.48, 0.5 , 0.46, 0.24, 0.35],
       [0.36, 0.42, 0.48, 0.5 , 0.53, 0.32, 0.41],
       [0.47, 0.46, 0.48, 0.5 , 0.62, 0.74, 0.77],
       [0.49, 0.61, 1.  , 0.5 , 0.56, 0.71, 0.74],
       [0.4 , 0.35, 0.48, 0.5 , 0.45, 0.33, 0.42],
       [0.52, 0.39, 0.48, 0.5 , 0.65, 0.71, 0.73],
       [0.2 , 0.46, 0.48, 0.5 , 0.57, 0.78, 0.81],
       [0.57, 0.38, 0.48, 0.5 , 0.06, 0.49, 0.33],
       [0.7 , 0.53, 0.48, 0.5 ,

In [31]:
y_test

array([0, 0, 1, 1, 2, 0, 3, 1, 2, 0, 4, 0, 0, 3, 3, 0, 1, 1, 3, 3, 2, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 2, 5, 0, 0, 2, 1, 2, 2, 0, 3, 3, 4, 2,
       4, 0, 2, 0, 3, 3, 2, 2, 0, 2, 0, 2, 1, 1, 0, 1, 0, 1, 0, 0, 3, 2,
       0, 5, 1, 4, 0, 0, 1, 0, 1, 1, 2, 4, 0, 0, 0, 2, 1, 0, 1, 1, 1, 4,
       4, 0, 2, 0, 1, 1, 0, 0, 3, 1, 0, 2, 1])

In [32]:
tp = TPOTClassifier(generations=5,population_size=100,verbosity=2)

In [33]:
tp.fit(x_train,y_train)

                                                                               
Generation 1 - Current best internal CV score: 0.8893617021276597
                                                                              
Generation 2 - Current best internal CV score: 0.8893617021276597
                                                                              
Generation 3 - Current best internal CV score: 0.8893617021276597
                                                                              
Generation 4 - Current best internal CV score: 0.8936170212765957
                                                                              
Generation 5 - Current best internal CV score: 0.8936170212765957
                                                                              
Best pipeline: ExtraTreesClassifier(input_matrix, bootstrap=False, criterion=entropy, max_features=1.0, min_samples_leaf=1, min_samples_split=9, n_estimators=100)


TPOTClassifier(generations=5, verbosity=2)

In [34]:
tp.score(x_test,y_test)

0.8712871287128713

In [35]:
tp.export('tpot_ecoli_pipeline.py')