In [1]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.utils import resample
from sklearn.decomposition import PCA

Dataset

In [2]:
data = pd.read_csv('./MalwareArtifacts.csv')

Eksplorasi Data

In [3]:
data.head()

AddressOfEntryPoint  MajorLinkerVersion  MajorImageVersion  \
0                10407                   9                  6   
1                 5354                   9                  6   
2                58807                   9                  6   
3                25166                   9                  6   
4                70387                   9                  6   

   MajorOperatingSystemVersion  DllCharacteristics  SizeOfStackReserve  \
0                            6               33088              262144   
1                            6               33088              262144   
2                            6               33088              262144   
3                            6               33088              262144   
4                            6               33088              262144   

   NumberOfSections  ResourceSize  legitimate  
0                 4           952           1  
1                 4           952           1  
2                 4        136490           1  
3                 4          1940           1  
4                 4         83098           1

In [4]:
data.tail()

AddressOfEntryPoint  MajorLinkerVersion  MajorImageVersion  \
137439               123291                  11                  0   
137440                40000                   2                  6   
137441                59610                  10                  0   
137442                51216                   2                  0   
137443                22731                  11                  0   

        MajorOperatingSystemVersion  DllCharacteristics  SizeOfStackReserve  \
137439                            5               33088             1048576   
137440                            1               32768             1048576   
137441                            5               33088             1048576   
137442                            1                   0             1048576   
137443                            5               33088             1048576   

        NumberOfSections  ResourceSize  legitimate  
137439                 5         81654           0  
137440                 8         67624           0  
137441                 5         22648           0  
137442                 8          2216           0  
137443                 5        318464           0

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 137444 entries, 0 to 137443
Data columns (total 9 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   AddressOfEntryPoint          137444 non-null  int64
 1   MajorLinkerVersion           137444 non-null  int64
 2   MajorImageVersion            137444 non-null  int64
 3   MajorOperatingSystemVersion  137444 non-null  int64
 4   DllCharacteristics           137444 non-null  int64
 5   SizeOfStackReserve           137444 non-null  int64
 6   NumberOfSections             137444 non-null  int64
 7   ResourceSize                 137444 non-null  int64
 8   legitimate                   137444 non-null  int64
dtypes: int64(9)
memory usage: 9.4 MB


In [6]:
print(data.shape)

(137444, 9)


In [7]:
data.describe()

AddressOfEntryPoint  MajorLinkerVersion  MajorImageVersion  \
count         1.374440e+05       137444.000000      137444.000000   
mean          1.722186e+05            8.620784          68.731876   
std           3.438014e+06            4.095635        1185.709873   
min           0.000000e+00            0.000000           0.000000   
25%           1.272100e+04            8.000000           0.000000   
50%           5.300800e+04            9.000000           0.000000   
75%           6.157800e+04           10.000000           6.000000   
max           1.074484e+09          255.000000       28619.000000   

       MajorOperatingSystemVersion  DllCharacteristics  SizeOfStackReserve  \
count                137444.000000       137444.000000        1.374440e+05   
mean                      5.098738        22301.043436        9.306841e+05   
std                      99.437584        15444.753219        5.553175e+05   
min                       0.000000            0.000000        0.000000e+00   
25%                       4.000000          320.000000        1.048576e+06   
50%                       5.000000        33088.000000        1.048576e+06   
75%                       5.000000        33088.000000        1.048576e+06   
max                   36868.000000        49504.000000        3.355443e+07   

       NumberOfSections  ResourceSize     legitimate  
count     137444.000000  1.374440e+05  137444.000000  
mean           4.997119  2.474766e+05       0.297707  
std            1.917237  2.129516e+07       0.457252  
min            1.000000  0.000000e+00       0.000000  
25%            4.000000  2.216000e+03       0.000000  
50%            5.000000  9.640000e+03       0.000000  
75%            5.000000  2.376250e+04       1.000000  
max           40.000000  4.294903e+09       1.000000

In [8]:
data["legitimate"].value_counts()

legitimate
0    96526
1    40918
Name: count, dtype: int64

Cleaning Data

In [9]:
data.isnull().sum()

AddressOfEntryPoint            0
MajorLinkerVersion             0
MajorImageVersion              0
MajorOperatingSystemVersion    0
DllCharacteristics             0
SizeOfStackReserve             0
NumberOfSections               0
ResourceSize                   0
legitimate                     0
dtype: int64

In [10]:
data.duplicated().sum()

104774

In [11]:
data.drop_duplicates(inplace=True)
data.duplicated().sum()

0

Pembagian Dataset

In [12]:
X = data.drop('legitimate', axis=1)
y = data['legitimate']

In [13]:
pca = PCA(n_components=2)
X = pca.fit_transform(X)

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("X_train = ", len(X_train))
print("X_test = ", len(X_test))
print("y_train = ", len(y_train))
print("y_test = ", len(y_test))

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

X_train =  26136
X_test =  6534
y_train =  26136
y_test =  6534
(26136, 2)
(6534, 2)
(26136,)
(6534,)


In [15]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler_X_train=scaler.fit_transform(X_train)
scaler_X_train

array([[-0.01899933, -0.0488071 ],
       [-0.01902344, -0.04232792],
       [-0.0190057 , -0.04491736],
       ...,
       [-0.01899526, -0.04708197],
       [-0.01900612, -0.04389276],
       [-0.01900459, -0.04795845]])

In [16]:
scaler_X_test=scaler.transform(X_test)
scaler_X_test

array([[-0.01878884,  0.00993905],
       [-0.01900238,  0.00403966],
       [-0.01900246, -0.04806905],
       ...,
       [-0.01856331, -0.04799501],
       [-0.01852547, -0.04809338],
       [-0.01900634, -0.04795222]])

Naive Bayes

In [17]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [18]:
y_pred = classifier.predict(X_test)
y_pred

array([1, 1, 1, ..., 1, 1, 1])

In [19]:
from sklearn.metrics import classification_report
akurasi = classification_report(y_test, y_pred)
print(akurasi)

              precision    recall  f1-score   support

           0       0.49      0.03      0.05      1779
           1       0.73      0.99      0.84      4755

    accuracy                           0.73      6534
   macro avg       0.61      0.51      0.45      6534
weighted avg       0.67      0.73      0.63      6534



SVM

In [20]:
from sklearn.svm import SVC

In [21]:
clf = SVC(kernel='linear') # Linear Kernel

In [22]:
#clf.fit(X_train, y_train)

In [23]:
#y_pred = clf.predict(X_test)

In [24]:
#from sklearn.metrics import confusion_matrix
#onfusion_matrix(y_test, y_pred)

In [25]:
#print(classification_report(y_test, y_pred))

In [26]:
import numpy as np


In [27]:
def predict_ensemble(models,x):
    predictions = np.array([model.predict(x) for model in models])
    majority_vote = np.apply_along_axis(lambda x: np.argmax(np.bincount(x)), axis=0, arr=predictions)
    return majority_vote

In [28]:
svm_models = []
total = 0
for i in range(50):
    x_boot, y_boot = resample(X_train, y_train, replace=True, n_samples = 20)
    print(len(x_boot))
    svm = SVC(kernel='linear')
    svm.fit(x_boot, y_boot)
    svm_models.append(svm)
    total += 1
    print(total)


20
1
20
2
20
3
20
4
20
5
20
6
20
7
20
8
20
9
20
10
20
11
20
12
20
13
20
14
20
15
20
16
20
17
20
18
20
19
20
20
20
21
20
22
20
23
20
24
20
25
20
26
20
27
20
28
20
29
20
30
20
31
20
32
20
33
20
34
20


In [ ]:
y_pred = predict_ensemble(svm_models, X_test)

In [ ]:
akurasi = classification_report(y_test, y_pred)
print(akurasi)

              precision    recall  f1-score   support

           0       0.42      0.11      0.18      1779
           1       0.74      0.94      0.83      4755

    accuracy                           0.72      6534
   macro avg       0.58      0.53      0.50      6534
weighted avg       0.65      0.72      0.65      6534

